NICKNAMES2NAMES = {
"wukong" : "Wukong",
"wu" : "Wukong",
"kong" : "Wukong",
"jax" : "Jax", 
"shaco" : "Shaco",
"faco" : "Shaco",
"warwick" : "Warwick",
"ww" : "Warwick",
"war wick" : "Warwick",
"nidalee" : "Nidalee",
"midalee" : "Nidalee",
"nid" : "Nidalee",
"zyra" : "Zyra", 
"kled" : "Kled",
"brand" : "Brand",
"rammus" : "Rammus",
"illaoi" : "Illaoi",
"ill" : "Illaoi",
"il" : "Illaoi",
"corki" : "Corki",
"yipsnakes" : "Corki",
"braum" : "Braum",
"darius" : "Darius",
"dar" : "Darius",
"tryndamere" : "Tryndamere",
"trynd" : "Tryndamere",
"tryn" : "Tryndamere",
"miss fortune" : "Miss Fortune",
"missfortune" : "Miss Fortune",
"miss" : "Miss Fortune",
"fortune" : "Miss Fortune",
"mf" : "Miss Fortune",
"sarah" : "Miss Fortune",
"yorick" : "Yorick",
"yor" : "Yorick",
"mori" : "Yorick",
"xerath" : "Xerath",
"xer" : "Xerath",
"sivir" : "Sivir",
"siv" : "Sivir",
"riven" : "Riven",
"riv" : "Riven",
"orianna" : "Orianna",
"ori" : "Orianna",
"gangplank" : "Gangplank",
"gankplank" : "Gangplank",
"tankplank" : "Gangplank",
"critplank" : "Gangplank",
"plank" : "Gangplank",
"gang" : "Gangplank",
"gp" : "Gangplank",
"malphite" : "Malphite",
"malph" : "Malphite",
"poppy" : "Poppy",
"karthus" : "Karthus",
"kar" : "Karthus",
"jayce" : "Jayce",
"jay" : "Jayce",
"nunu" : "Nunu",
"willump" : "Nunu",
"trundle" : "Trundle",
"trund" : "Trundle",
"ruhgosk" : "Trundle",
"graves" : "Graves",
"malcolm" : "Graves",
"morgana" : "Morgana",
"morg" : "Morgana",
"gnar" : "Gnar",
"lux" : "Lux",
"luxanna" : "Lux",
"shyvana" : "Shyvana",
"shyv" : "Shyvana",
"ren" : "Renekton",
"rekt" : "Renekton",
"rene" : "Renekton",
"renek" : "Renekton",
"fiora" : "Fiora",
"fi" : "Fiora",
"laurent" : "Fiora",
"jinx" : "Jinx",
"x" : "Jinx",
"kalista" : "Kalista",
"kal" : "Kalista",
"fizz" : "Fizz",
"fiz" : "Fizz",
"kassadin" : "Kassadin",
"kass" : "Kassadin",
"kas" : "Kassadin",
"sona" : "Sona",
"irelia" : "Irelia",
"viktor" : "Viktor",
"vik" : "Viktor",
"kindred" : "Kindred",
"kind" : "Kindred",
"kin" : "Kindred",
"wolf" : "Kindred",
"lamb" : "Kindred",
"cassiopeia" : "Cassiopeia",
"cass" : "Cassiopeia",
"cas" : "Cassiopeia",
"maokai" : "Maokai",
"mao" : "Maokai",
"thresh" : "Thresh",
"kayle" : "Kayle",
"hecarim" : "Hecarim",
"hec" : "Hecarim",
"kha'zix" : "Kha'Zix",
"khazix" : "Kha'Zix",
"kha zix" : "Kha'Zix",
"kha" : "Kha'Zix",
"zix" : "Kha'Zix",
"olaf" : "Olaf",
"lokfar" : "Olaf",
"ziggs" : "Ziggs",
"zigs" : "Ziggs",
"zigg" : "Ziggs",
"zig" : "Ziggs",
"syndra" : "Syndra",
"synd" : "Syndra",
"syn" : "Syndra",
"dr mundo" : "Dr. Mundo",
"dr. mundo" : "Dr. Mundo",
"dr.mundo" : "Dr. Mundo",
"drmundo" : "Dr. Mundo",
"dr." : "Dr. Mundo",
"dr" : "Dr. Mundo",
"mundo" : "Dr. Mundo",
"karma" : "Karma",
"karm" : "Karma",
"kar" : "Karma",
"annie" : "Annie",
"hastur" : "Annie",
"akali" : "Akali",
"kali" : "Akali",
"volibear" : "Volibear",
"voli" : "Volibear",
"bear" : "Volibear",
"yasuo" : "Yasuo",
"yas" : "Yasuo",
"kennen" : "Kennen",
"kenn" : "Kennen",
"ken" : "Kennen",
"reng" : "Rengar",
"ren" : "Rengar",
"rengar" : "Rengar",
"ryze" : "Ryze",
"shen" : "Shen",
"zac" : "Zac",
"zack" : "Zac",
"zak" : "Zac",
"talon" : "Talon",
"tal" : "Talon",
"swain" : "Swain",
"jericho" : "Swain",
"bard" : "Bard",
"sion" : "Sion",
"vayne" : "Vayne",
"vayn" : "Vayne",
"shauna" : "Vayne",
"nasus" : "Nasus",
"nas" : "Nasus",
"susan" : "Nasus",
"fiddlesticks" : "Fiddlesticks",
"fiddle" : "Fiddlesticks",
"fiddle sticks" : "Fiddlesticks",
"sticks" : "Fiddlesticks",
"fidd" : "Fiddlesticks",
"fid" : "Fiddlesticks",
"fidds" : "Fiddlesticks",
"fids" : "Fiddlesticks",
"twisted fate" : "Twisted Fate",
"twistedfate" : "Twisted Fate",
"tf" : "Twisted Fate",
"twisted" : "Twisted Fate",
"fate" : "Twisted Fate",
"tobias" : "Twisted Fate",
"cho'gath" : "Cho'Gath", 
"chogath" : "Cho'Gath", 
"cho gath" : "Cho'Gath", 
"cho" : "Cho'Gath", 
"gath" : "Cho'Gath", 
"udyr" : "Udyr",
"lucian" : "Lucian",
"luc" : "Lucian",
"ivern" : "Ivern",
"leona" : "Leona",
"leo" : "Leona",
"caitlyn" : "Caitlyn",
"cait" : "Caitlyn",
"cat" : "Caitlyn",
"sejuani" : "Sejuani",
"sej" : "Sejuani",
"nocturne" : "Nocturne",
"noct" : "Nocturne",
"noc" : "Nocturne",
"zilean" : "Zilean", 
"zil" : "Zilean",
"azir" : "Azir",
"rumble" : "Rumble",
"taliyah" : "Taliyah",
"tali" : "Taliyah",
"tal" : "Taliyah",
"taliyeah" : "Taliyah",
"satan" : "Teemo",
"teemo" : "Teemo",
"devil" : "Teemo",
"demon" : "Teemo",
"urgot" : "Urgot",
"amumu" : "Amumu",
"galio" : "Galio",
"gal" : "Galio",
"heimer" : "Heimerdinger",
"heim" : "Heimerdinger",
"dinger" : "Heimerdinger",
"donger" : "Heimerdinger",
"heimerdonger" : "Heimerdinger",
"anivia" : "Anivia",
"articuno" : "Anivia",
"ashe" : "Ashe",
"ash" : "Ashe",
"vel'koz" : "Vel'Koz",
"vel koz" : "Vel'Koz",
"velkoz" : "Vel'Koz",
"vel" : "Vel'Koz",
"koz" : "Vel'Koz",
"singed" : "Singed",
"skarner" : "Skarner",
"varus" : "Varus",
"twitch" : "Twitch",
"garen" : "Garen",
"blitzcrank" : "Blitzcrank",
"blitz" : "Blitzcrank",
"master yi" : "Master Yi",
"masteryi" : "Master Yi",
"master" : "Master Yi",
"yi" : "Master Yi",
"my" : "Master Yi",
"elise" : "Elise",
"alistar" : "Alistar",
"ali" : "Alistar",
"kat" : "Katarina",
"katatina" : "Katarina",
"ekko" : "Ekko",
"xii" : "Ekko",
"mordekaiser" : "Mordekaiser",
"morde" : "Mordekaiser",
"mord" : "Mordekaiser",
"lulu" : "Lulu",
"cam" : "Camille",
"camille" : "Camille",
"aatrox" : "Aatrox",
"trox" : "Aatrox",
"atrox" : "Aatrox",
"draven" : "Draven",
"tahm kench" : "Tahm Kench",
"tahmkench" : "Tahm Kench",
"tahm" : "Tahm Kench",
"tom" : "Tahm Kench",
"kench" : "Tahm Kench",
"tom kench" : "Tahm Kench",
"tomkench" : "Tahm Kench",
"pantheon" : "Pantheon", 
"panth" : "Pantheon",
"mantheon" : "Pantheon",
"xin zhao" : "Xin Zhao",
"xinzhao" : "Xin Zhao",
"xin" : "Xin Zhao",
"zhao" : "Xin Zhao",
"xz" : "Xhin Zhao",
"aurelion sol" : "Aurelion Sol",
"aurelionsol" : "Aurelion Sol",
"a sol" : "Aurelion Sol",
"aurelion" : "Aurelion Sol",
"sol" : "Aurelion Sol",
"asol" : "Aurelion Sol",
"a. sol" : "Aurelion Sol",
"a.sol" : "Aurelion Sol",
"as" : "Aurelion Sol",
"a.s" : "Aurelion Sol",
"lee sin" : "Lee Sin",
"leesin" : "Lee Sin",
"lee" : "Lee Sin",
"sin" : "Lee Sin",
"ls" : "Lee Sin",
"taric" : "Taric",
"malzahar" : "Malzahar",
"malz" : "Malzahar",
"mals" : "Malzahar",
"lissandra" : "Lissandra",
"liss" : "Lissandra",
"lis" : "Lissandra",
"diana" : "Diana",
"di" : "Diana",
"tristana" : "Tristana",
"trist" : "Tristana",
"rek'sai" : "Rek'Sai",
"rek sai" : "Rek'Sai",
"reksai" : "Rek'Sai",
"rek" : "Rek'Sai",
"sai" : "Rek'Sai",
"vladimir" : "Vladimir",
"vlad" : "Vladimir",
"jarvan iv" : "Jarvan IV", 
"jarvaniv" : "Jarvan IV", 
"jarvan" : "Jarvan IV", 
"iv" : "Jarvan IV", 
"jiv" : "Jarvan IV", 
"j4" : "Jarvan IV",
"lightshield" : "Jarvan IV", 
"nami" : "Nami",
"jhin" : "Jhin",
"john" : "Jhin",
"soraka" : "Soraka",
"raka" : "Soraka",
"veigar" : "Veigar",
"janna" : "Janna",
"nautilus" : "Nautilus",
"naut" : "Nautilus",
"evelynn" : "Evelynn",
"eve" : "Evelynn",
"evelyn" : "Evelynn",
"gragas" : "Gragas",
"grag" : "Gragas",
"zed" : "Zed",
"zedd" : "Zed",
"vi" : "Vi",
"kog'maw" : "Kog'Maw",
"kog maw" : "Kog'Maw",
"kogmaw" : "Kog'Maw",
"kog" : "Kog'Maw",
"maw" : "Kog'Maw",
"ahri" : "Ahri",
"quinn" : "Quinn",
"valor" : "Quinn",
"quin" : "Quinn",
"leblanc" : "LeBlanc",
"lb" : "LeBlanc",
"ezreal" : "Ezreal",
"ez" : "Ezreal"
}
